name: CI/CD

on:
  push:
    branches:
      - main
      - master
      - develop
      - feature/*
  pull_request:
    branches:
      - main
      - master
      - develop
      - feature/*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Force Node.js 20
        run: echo "FORCE_JAVASCRIPT_ACTIONS_TO_NODE20=true" >> $GITHUB_ENV

      - name: Checkout code
        uses: actions/checkout@v3

      - name: List files
        run: ls -la  # Vérifiez la présence de package.json

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install --legacy-peer-deps  # Ou --force si nécessaire

      - name: Build the project
        run: npm run build  # Remplacez par votre commande de build

      - name: Run tests
        run: npm test  # Remplacez par votre commande de test

  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Server
        uses: appleboy/scp-action@v0.2.1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "dist/"
          target: "/var/www/html/"

  cypress:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          start: npm start
          wait-on: 'http://localhost:3000'  # Ajustez selon votre application
          wait-on-timeout: 60
