name: CI

on:
  push:
    branches:
      - main  # ou la branche que vous souhaitez surveiller
  pull_request:
    branches:
      - main  # ou la branche que vous souhaitez surveiller

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Utilisation de la version 3

      - name: Set up Node.js
        uses: actions/setup-node@v3  # Utilisation de la version 3
        with:
          node-version: '20'  # Spécifiez la version de Node.js (20 ou plus)

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build  # Remplacez par votre commande de build

      - name: Run tests
        run: npm test  # Remplacez par votre commande de test

      - name: Deploy
        run: |
          echo "Déployer votre application ici"
          # Ajoutez les commandes pour déployer votre application
