name: CI

on:
  push:
    branches:
      - develop
      - main
      - feature/*
  pull_request:
    branches:
      - develop
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'  # Utilisation de Node.js 20

      - name: Install dependencies
        run: npm install

      - name: Print environment
        run: |
          node -v
          npm -v
          npm list

      - name: Run tests
        run: npm test || echo "No tests found"

      - name: Build
        run: npm run build
