name: CI

on:
  push:
    branches:
      - develop
      - main
      - feature/*
  pull_request:
    branches:
      - develop
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Mettez à jour vers la version 3

      - name: Set up Node.js
        uses: actions/setup-node@v3  # Mettez à jour vers la version 3
        with:
          node-version: '20'  # Assurez-vous d'utiliser la version 20

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test || echo "No tests found"

      - name: Build
        run: npm run build
